"""Remove id_traduction

Revision ID: 3a2e9399a5a9
Revises: 3a6eb0d93be5
Create Date: 2026-10-05 16:55:16.737837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a2e9399a5a9'
down_revision: Union[str, Sequence[str], None] = '3a6eb0d93be5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sentences_id_traduction'), table_name='sentences')
    op.drop_column('sentences', 'id_traduction')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentences', sa.Column('id_traduction', sa.INTEGER(), nullable=True))
    op.create_index(op.f('ix_sentences_id_traduction'), 'sentences', ['id_traduction'], unique=False)
    # ### end Alembic commands ###
