"""Add dictionary schema

Revision ID: 3a6eb0d93be5
Revises: a11dd51166ec
Create Date: 2026-10-05 16:52:28.379397

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a6eb0d93be5'
down_revision: Union[str, Sequence[str], None] = 'a11dd51166ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tags_id'), 'tags', ['id'], unique=False)
    op.create_index(op.f('ix_tags_type'), 'tags', ['type'], unique=False)
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_id'), 'word', ['id'], unique=False)
    op.create_index(op.f('ix_word_word'), 'word', ['word'], unique=True)
    op.create_table('explanation',
    sa.Column('id_word', sa.Integer(), nullable=False),
    sa.Column('traduction', sa.String(), nullable=False),
    sa.Column('examples', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_word'], ['word.id'], ),
    sa.PrimaryKeyConstraint('id_word')
    )
    op.create_table('word_tag',
    sa.Column('id_word', sa.Integer(), nullable=False),
    sa.Column('id_tag', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_tag'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['id_word'], ['word.id'], ),
    sa.PrimaryKeyConstraint('id_word', 'id_tag')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_tag')
    op.drop_table('explanation')
    op.drop_index(op.f('ix_word_word'), table_name='word')
    op.drop_index(op.f('ix_word_id'), table_name='word')
    op.drop_table('word')
    op.drop_index(op.f('ix_tags_type'), table_name='tags')
    op.drop_index(op.f('ix_tags_id'), table_name='tags')
    op.drop_table('tags')
    # ### end Alembic commands ###
